name: seiRelease-5.1.0-carga-mysql

on:
  push:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/testCarga.yml
    secrets: inherit
    with:
      sei-version: release/5.1.0
      db: mysql
