name: sei4.0.12.15-carga-mysql

on:
  push:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/testCarga.yml
    secrets: inherit
    with:
      sei-version: 4.0.12.15
      db: mysql
