name: Testes

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - sei: 4.1.5
          - sei: 5.0.4
          - sei: release/5.1.0
    steps:
      - name: Checkout Me
        uses: actions/checkout@v7
        with:
            path: sei-loadtests
            ref: feat/marlinhares-sei5

      - name: Fetch SEI
        uses: actions/checkout@v7
        with:
          repository: pengovbr/sei
          token: ${{ secrets.GH_PAT }}
          path: sei-loadtests/tests/assets/repos/sei-fontes
          ref: ${{ matrix.sei }}

      - name: Fetch sei-docker
        uses: actions/checkout@v7
        with:
          repository: pengovbr/sei-docker
          path: sei-loadtests/tests/assets/repos/sei-docker

      - name: RunTests
        run: |
          ls -lha sei-loadtests
          cd sei-loadtests/tests
          make sei-setup && make jmeter-run
