name: Teste Versao

on:
  workflow_run:
    workflows: ["Pre Teste Versao"]
    types:
      - completed

jobs:

  test:
    runs-on: ubuntu-latest
    if: ${{ gitevents.workflow_run.conclusion == 'success' }}

    steps:

      - name: Get SEI-version parameter
        uses: actions/download-artifact@v4
        with:
          name: myparameter
          path: ./sei-version.parameter

      - name: Read SEI-version parameter
        run: |
          SEI_VERSION=$(cat ./sei-version.parameter)
          echo "SEI_VERSION=$SEI_VERSION" >> $GITHUB_ENV

      - name: Checkout Me
        uses: actions/checkout@v7
        with:
            path: sei-loadtests

      - name: Fetch SEI
        uses: actions/checkout@v7
        with:
          repository: pengovbr/sei
          token: ${{ secrets.GH_PAT }}
          path: sei-loadtests/tests/assets/repos/sei-fontes
          ref: ${{ env.SEI_VERSION }}

      - name: Fetch sei-docker
        uses: actions/checkout@v7
        with:
          repository: pengovbr/sei-docker
          path: sei-loadtests/tests/assets/repos/sei-docker

      - name: RunTests
        run: |
          cd sei-loadtests/tests
          make test

      - name: Archive test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: sei-loadtests/tests/assets/test-results/result-testes.jtl
