name: Carga

on:

  workflow_dispatch:
    inputs:
      sei-version:
        required: true
        type: string
      db:
        required: true
        type: string
        default: mysql

  workflow_call:
    inputs:
      sei-version:
        required: true
        type: string
      db:
        required: true
        type: string
        default: mysql

jobs:

  carga:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Me
        uses: actions/checkout@v7
        with:
            path: sei-loadtests

      - name: Fetch SEI
        uses: actions/checkout@v7
        with:
          repository: pengovbr/sei
          token: ${{ secrets.GH_PAT }}
          path: sei-loadtests/tests/assets/repos/sei-fontes
          ref: ${{ inputs.sei-version }}

      - name: Fetch sei-docker
        uses: actions/checkout@v7
        with:
          repository: pengovbr/sei-docker
          path: sei-loadtests/tests/assets/repos/sei-docker

      - name: RunCarga
        run: |
          cd sei-loadtests/tests
          make DB=${{ inputs.db }} carga

      - name: Archive carga artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: carga-results
          path: sei-loadtests/tests/assets/testResults/result-test.jtl

